# SPDX-License-Identifier: MIT
# CI Engine - Comprehensive Skill Definitions

from typing import Optional
from dataclasses import dataclass


SKILL_CATEGORIES = {
    "build": {"display_name": "Build", "description": "Build tools and package managers"},
    "test": {"display_name": "Test", "description": "Testing frameworks"},
    "deploy": {"display_name": "Deploy", "description": "Deployment tools"},
    "security": {"display_name": "Security", "description": "Security scanning"},
    "code_quality": {"display_name": "Code Quality", "description": "Linting and formatting"},
    "infrastructure": {"display_name": "Infrastructure", "description": "Cloud providers"},
    "scripting": {"display_name": "Scripting", "description": "Language runtimes"},
    "databases": {"display_name": "Databases", "description": "Database operations"},
    "monitoring": {"display_name": "Monitoring", "description": "Observability"},
    "communication": {"display_name": "Communication", "description": "Notifications"},
    "container": {"display_name": "Container", "description": "Container tools"},
    "git": {"display_name": "Git", "description": "Version control"},
    "analytics": {"display_name": "Analytics", "description": "Code analysis"},
    "documentation": {"display_name": "Documentation", "description": "Doc generation"},
    "package": {"display_name": "Package", "description": "Package management"},
    "compliance": {"display_name": "Compliance", "description": "Policy enforcement"},
}


@dataclass
class SkillDefinition:
    name: str
    display_name: str
    category: str
    description: str
    detect_command: str
    min_version: Optional[str] = None
    version_regex: Optional[str] = None
    required_tools: Optional[list[str]] = None
    tags: Optional[list[str]] = None
    skill_level_default: int = 1

    def __post_init__(self):
        if self.required_tools is None:
            self.required_tools = []
        if self.tags is None:
            self.tags = []


SKILL_DEFINITIONS: dict[str, SkillDefinition] = {
    # ==================== BUILD ====================
    "docker": SkillDefinition(
        name="docker",
        display_name="Docker",
        category="build",
        description="Container build and run",
        detect_command="docker --version",
        version_regex=r"(\d+\.\d+)",
        tags=["container", "devops", "cloud"],
    ),
    "podman": SkillDefinition(
        name="podman",
        display_name="Podman",
        category="build",
        description="Container runtime (rootless)",
        detect_command="podman --version",
        version_regex=r"(\d+\.\d+)",
        tags=["container", "devops"],
    ),
    "make": SkillDefinition(
        name="make",
        display_name="Make",
        category="build",
        description="Build automation",
        detect_command="make --version",
        version_regex=r"(\d+\.\d+)",
        tags=["build", "automation"],
    ),
    "cmake": SkillDefinition(
        name="cmake",
        display_name="CMake",
        category="build",
        description="Cross-platform build system",
        detect_command="cmake --version",
        version_regex=r"cmake version (\d+\.\d+)",
        tags=["build", "c++"],
    ),
    "gradle": SkillDefinition(
        name="gradle",
        display_name="Gradle",
        category="build",
        description="Java/Kotlin build tool",
        detect_command="gradle --version",
        version_regex=r"Gradle (\d+\.\d+)",
        tags=["java", "kotlin", "build"],
    ),
    "maven": SkillDefinition(
        name="maven",
        display_name="Maven",
        category="build",
        description="Java build tool",
        detect_command="mvn --version",
        version_regex=r"Apache Maven (\d+\.\d+)",
        tags=["java", "build"],
    ),
    "npm": SkillDefinition(
        name="npm",
        display_name="npm",
        category="build",
        description="Node.js package manager",
        detect_command="npm --version",
        version_regex=r"(\d+\.\d+)",
        tags=["nodejs", "javascript", "package"],
    ),
    "yarn": SkillDefinition(
        name="yarn",
        display_name="Yarn",
        category="build",
        description="Node.js package manager (alternative)",
        detect_command="yarn --version",
        version_regex=r"(\d+\.\d+)",
        tags=["nodejs", "javascript", "package"],
    ),
    "pnpm": SkillDefinition(
        name="pnpm",
        display_name="pnpm",
        category="build",
        description="Fast, disk space efficient package manager",
        detect_command="pnpm --version",
        version_regex=r"(\d+\.\d+)",
        tags=["nodejs", "package"],
    ),
    "dotnet": SkillDefinition(
        name="dotnet",
        display_name=".NET",
        category="build",
        description="Microsoft .NET SDK",
        detect_command="dotnet --version",
        version_regex=r"(\d+\.\d+)",
        tags=["csharp", "windows", "build"],
    ),
    "bazel": SkillDefinition(
        name="bazel",
        display_name="Bazel",
        category="build",
        description="Fast, scalable build system",
        detect_command="bazel --version",
        version_regex=r"(\d+\.\d+)",
        tags=["build", "google"],
    ),
    "cargo": SkillDefinition(
        name="cargo",
        display_name="Cargo",
        category="build",
        description="Rust package manager",
        detect_command="cargo --version",
        version_regex=r"(\d+\.\d+)",
        tags=["rust", "build"],
    ),
    # ==================== TEST ====================
    "pytest": SkillDefinition(
        name="pytest",
        display_name="Pytest",
        category="test",
        description="Python testing framework",
        detect_command="pytest --version",
        version_regex=r"(\d+\.\d+)",
        tags=["python", "testing"],
    ),
    "unittest": SkillDefinition(
        name="unittest",
        display_name="unittest",
        category="test",
        description="Python unit testing framework",
        detect_command="python -c 'import unittest; print(unittest.__version__)'",
        tags=["python", "testing"],
    ),
    "jest": SkillDefinition(
        name="jest",
        display_name="Jest",
        category="test",
        description="JavaScript testing framework",
        detect_command="jest --version",
        version_regex=r"(\d+\.\d+)",
        tags=["javascript", "testing", "nodejs"],
    ),
    "vitest": SkillDefinition(
        name="vitest",
        display_name="Vitest",
        category="test",
        description="Fast Vite-native testing framework",
        detect_command="vitest --version",
        version_regex=r"(\d+\.\d+)",
        tags=["javascript", "testing", "nodejs"],
    ),
    "mocha": SkillDefinition(
        name="mocha",
        display_name="Mocha",
        category="test",
        description="JavaScript test framework",
        detect_command="mocha --version",
        version_regex=r"(\d+\.\d+)",
        tags=["javascript", "testing"],
    ),
    "testng": SkillDefinition(
        name="testng",
        display_name="TestNG",
        category="test",
        description="Java testing framework",
        detect_command="testng --version 2>&1 || echo 'not found'",
        tags=["java", "testing"],
    ),
    "junit": SkillDefinition(
        name="junit",
        display_name="JUnit",
        category="test",
        description="Java unit testing framework",
        detect_command="junit --version 2>&1 || echo 'not found'",
        tags=["java", "testing"],
    ),
    "cypress": SkillDefinition(
        name="cypress",
        display_name="Cypress",
        category="test",
        description="End-to-end testing for web",
        detect_command="cypress --version",
        version_regex=r"(\d+\.\d+)",
        tags=["javascript", "e2e", "testing"],
    ),
    "playwright": SkillDefinition(
        name="playwright",
        display_name="Playwright",
        category="test",
        description="Cross-browser end-to-end testing",
        detect_command="playwright --version",
        version_regex=r"(\d+\.\d+)",
        tags=["javascript", "e2e", "testing"],
    ),
    "selenium": SkillDefinition(
        name="selenium",
        display_name="Selenium",
        category="test",
        description="Browser automation framework",
        detect_command="selenium --version 2>&1 || echo 'not found'",
        tags=["automation", "testing", "web"],
    ),
    "k6": SkillDefinition(
        name="k6",
        display_name="k6",
        category="test",
        description="Load testing tool",
        detect_command="k6 version",
        version_regex=r"(\d+\.\d+)",
        tags=["load", "performance", "testing"],
    ),
    "gatling": SkillDefinition(
        name="gatling",
        display_name="Gatling",
        category="test",
        description="Load testing framework",
        detect_command="gatling --version 2>&1 || echo 'not found'",
        tags=["load", "performance", "testing"],
    ),
    "locust": SkillDefinition(
        name="locust",
        display_name="Locust",
        category="test",
        description="Python load testing tool",
        detect_command="locust --version",
        version_regex=r"(\d+\.\d+)",
        tags=["load", "performance", "python"],
    ),
    # ==================== DEPLOY ====================
    "kubectl": SkillDefinition(
        name="kubectl",
        display_name="kubectl",
        category="deploy",
        description="Kubernetes CLI",
        detect_command="kubectl version --client --short",
        version_regex=r"(\d+\.\d+)",
        tags=["kubernetes", "cloud", "deploy"],
    ),
    "helm": SkillDefinition(
        name="helm",
        display_name="Helm",
        category="deploy",
        description="Kubernetes package manager",
        detect_command="helm version",
        version_regex=r"(\d+\.\d+)",
        tags=["kubernetes", "cloud", "deploy"],
    ),
    "terraform": SkillDefinition(
        name="terraform",
        display_name="Terraform",
        category="deploy",
        description="Infrastructure as Code",
        detect_command="terraform version",
        version_regex=r"(\d+\.\d+)",
        tags=["iac", "infrastructure", "aws"],
    ),
    "ansible": SkillDefinition(
        name="ansible",
        display_name="Ansible",
        category="deploy",
        description="Configuration management",
        detect_command="ansible --version",
        version_regex=r"(\d+\.\d+)",
        tags=["automation", "config", "deploy"],
    ),
    "pulumi": SkillDefinition(
        name="pulumi",
        display_name="Pulumi",
        category="deploy",
        description="Infrastructure as Code (developer-friendly)",
        detect_command="pulumi version",
        version_regex=r"(\d+\.\d+)",
        tags=["iac", "infrastructure"],
    ),
    "serverless": SkillDefinition(
        name="serverless",
        display_name="Serverless Framework",
        category="deploy",
        description="Serverless application framework",
        detect_command="serverless --version",
        version_regex=r"(\d+\.\d+)",
        tags=["serverless", "aws", "lambda"],
    ),
    "eksctl": SkillDefinition(
        name="eksctl",
        display_name="eksctl",
        category="deploy",
        description="EKS cluster management",
        detect_command="eksctl version",
        version_regex=r"(\d+\.\d+)",
        tags=["kubernetes", "aws", "eks"],
    ),
    "istio": SkillDefinition(
        name="istio",
        display_name="Istio",
        category="deploy",
        description="Service mesh for Kubernetes",
        detect_command="istioctl version",
        version_regex=r"(\d+\.\d+)",
        tags=["kubernetes", "service-mesh"],
    ),
    # ==================== SECURITY ====================
    "trivy": SkillDefinition(
        name="trivy",
        display_name="Trivy",
        category="security",
        description="Vulnerability scanner",
        detect_command="trivy --version",
        version_regex=r"(\d+\.\d+)",
        tags=["security", "vulnerability", "container"],
    ),
    "snyk": SkillDefinition(
        name="snyk",
        display_name="Snyk",
        category="security",
        description="Dependency vulnerability scanning",
        detect_command="snyk --version",
        version_regex=r"(\d+\.\d+)",
        tags=["security", "vulnerability", "sca"],
    ),
    "bandit": SkillDefinition(
        name="bandit",
        display_name="Bandit",
        category="security",
        description="Python security linter",
        detect_command="bandit --version",
        version_regex=r"(\d+\.\d+)",
        tags=["python", "security", "linter"],
    ),
    "checkov": SkillDefinition(
        name="checkov",
        display_name="Checkov",
        category="security",
        description="Infrastructure as Code scanner",
        detect_command="checkov --version",
        version_regex=r"(\d+\.\d+)",
        tags=["security", "iac", "terraform"],
    ),
    "tfsec": SkillDefinition(
        name="tfsec",
        display_name="tfsec",
        category="security",
        description="Terraform security scanner",
        detect_command="tfsec --version",
        version_regex=r"(\d+\.\d+)",
        tags=["security", "terraform", "iac"],
    ),
    "clair": SkillDefinition(
        name="clair",
        display_name="Clair",
        category="security",
        description="Container vulnerability scanner",
        detect_command="clairctl --version 2>&1 || echo 'not found'",
        tags=["security", "container", "vulnerability"],
    ),
    "semgrep": SkillDefinition(
        name="semgrep",
        display_name="Semgrep",
        category="security",
        description="Static analysis tool",
        detect_command="semgrep --version",
        version_regex=r"(\d+\.\d+)",
        tags=["security", "sast", "static-analysis"],
    ),
    "gosec": SkillDefinition(
        name="gosec",
        display_name="gosec",
        category="security",
        description="Go security scanner",
        detect_command="gosec --version",
        version_regex=r"(\d+\.\d+)",
        tags=["security", "go", "sast"],
    ),
    "hadolint": SkillDefinition(
        name="hadolint",
        display_name="Hadolint",
        category="security",
        description="Dockerfile linter",
        detect_command="hadolint --version",
        version_regex=r"(\d+\.\d+)",
        tags=["docker", "linter", "security"],
    ),
    # ==================== CODE QUALITY ====================
    "ruff": SkillDefinition(
        name="ruff",
        display_name="Ruff",
        category="code_quality",
        description="Fast Python linter",
        detect_command="ruff --version",
        version_regex=r"(\d+\.\d+)",
        tags=["python", "linter", "formatting"],
    ),
    "eslint": SkillDefinition(
        name="eslint",
        display_name="ESLint",
        category="code_quality",
        description="JavaScript/TypeScript linter",
        detect_command="eslint --version",
        version_regex=r"(\d+\.\d+)",
        tags=["javascript", "typescript", "linter"],
    ),
    "prettier": SkillDefinition(
        name="prettier",
        display_name="Prettier",
        category="code_quality",
        description="Code formatter",
        detect_command="prettier --version",
        version_regex=r"(\d+\.\d+)",
        tags=["javascript", "formatter", "formatting"],
    ),
    "pylint": SkillDefinition(
        name="pylint",
        display_name="Pylint",
        category="code_quality",
        description="Python code analyzer",
        detect_command="pylint --version",
        version_regex=r"(\d+\.\d+)",
        tags=["python", "linter"],
    ),
    "mypy": SkillDefinition(
        name="mypy",
        display_name="MyPy",
        category="code_quality",
        description="Python type checker",
        detect_command="mypy --version",
        version_regex=r"(\d+\.\d+)",
        tags=["python", "type-checker"],
    ),
    "golint": SkillDefinition(
        name="golint",
        display_name="golint",
        category="code_quality",
        description="Go linter",
        detect_command="golint --version 2>&1 || echo 'not found'",
        tags=["go", "linter"],
    ),
    "staticcheck": SkillDefinition(
        name="staticcheck",
        display_name="staticcheck",
        category="code_quality",
        description="Go static analysis",
        detect_command="staticcheck --version",
        version_regex=r"(\d+\.\d+)",
        tags=["go", "static-analysis"],
    ),
    "sonarlint": SkillDefinition(
        name="sonarlint",
        display_name="SonarLint",
        category="code_quality",
        description="IDE linter (also CLI)",
        detect_command="sonarlint --version 2>&1 || echo 'not found'",
        tags=["quality", "analysis"],
    ),
    "shellcheck": SkillDefinition(
        name="shellcheck",
        display_name="ShellCheck",
        category="code_quality",
        description="Shell script linter",
        detect_command="shellcheck --version",
        version_regex=r"(\d+\.\d+)",
        tags=["shell", "bash", "linter"],
    ),
    # ==================== INFRASTRUCTURE ====================
    "aws": SkillDefinition(
        name="aws",
        display_name="AWS CLI",
        category="infrastructure",
        description="Amazon Web Services CLI",
        detect_command="aws --version",
        version_regex=r"aws-cli/(\d+\.\d+)",
        tags=["cloud", "aws", "devops"],
    ),
    "gcloud": SkillDefinition(
        name="gcloud",
        display_name="gcloud",
        category="infrastructure",
        description="Google Cloud CLI",
        detect_command="gcloud --version",
        version_regex=r"(\d+\.\d+)",
        tags=["cloud", "gcp", "devops"],
    ),
    "az": SkillDefinition(
        name="az",
        display_name="Azure CLI",
        category="infrastructure",
        description="Microsoft Azure CLI",
        detect_command="az --version",
        version_regex=r"(\d+\.\d+)",
        tags=["cloud", "azure", "devops"],
    ),
    "packer": SkillDefinition(
        name="packer",
        display_name="Packer",
        category="infrastructure",
        description="Machine image builder",
        detect_command="packer --version",
        version_regex=r"(\d+\.\d+)",
        tags=["infrastructure", "cloud", "imaging"],
    ),
    "vault": SkillDefinition(
        name="vault",
        display_name="Vault",
        category="infrastructure",
        description="Secret management",
        detect_command="vault --version",
        version_regex=r"(\d+\.\d+)",
        tags=["security", "secrets", "infrastructure"],
    ),
    # ==================== SCRIPTING ====================
    "python": SkillDefinition(
        name="python",
        display_name="Python",
        category="scripting",
        description="Python runtime",
        detect_command="python --version",
        version_regex=r"Python (\d+\.\d+)",
        tags=["language", "scripting", "data"],
    ),
    "python3": SkillDefinition(
        name="python3",
        display_name="Python3",
        category="scripting",
        description="Python3 runtime",
        detect_command="python3 --version",
        version_regex=r"Python (\d+\.\d+)",
        tags=["language", "scripting"],
    ),
    "node": SkillDefinition(
        name="node",
        display_name="Node.js",
        category="scripting",
        description="Node.js runtime",
        detect_command="node --version",
        version_regex=r"v(\d+\.\d+)",
        tags=["language", "javascript", "runtime"],
    ),
    "ruby": SkillDefinition(
        name="ruby",
        display_name="Ruby",
        category="scripting",
        description="Ruby runtime",
        detect_command="ruby --version",
        version_regex=r"(\d+\.\d+)",
        tags=["language", "scripting"],
    ),
    "go": SkillDefinition(
        name="go",
        display_name="Go",
        category="scripting",
        description="Go runtime",
        detect_command="go version",
        version_regex=r"go(\d+\.\d+)",
        tags=["language", "runtime"],
    ),
    "bash": SkillDefinition(
        name="bash",
        display_name="Bash",
        category="scripting",
        description="Bash shell",
        detect_command="bash --version",
        version_regex=r"(\d+\.\d+)",
        tags=["shell", "scripting"],
    ),
    "zsh": SkillDefinition(
        name="zsh",
        display_name="Zsh",
        category="scripting",
        description="Zsh shell",
        detect_command="zsh --version",
        version_regex=r"(\d+\.\d+)",
        tags=["shell", "scripting"],
    ),
    "powershell": SkillDefinition(
        name="powershell",
        display_name="PowerShell",
        category="scripting",
        description="PowerShell",
        detect_command="pwsh --version 2>&1 || powershell -Command '$PSVersionTable.PSVersion' 2>&1 || echo 'not found'",
        tags=["shell", "windows", "scripting"],
    ),
    "perl": SkillDefinition(
        name="perl",
        display_name="Perl",
        category="scripting",
        description="Perl runtime",
        detect_command="perl --version",
        version_regex=r"v(\d+\.\d+)",
        tags=["language", "scripting"],
    ),
    "php": SkillDefinition(
        name="php",
        display_name="PHP",
        category="scripting",
        description="PHP runtime",
        detect_command="php --version",
        version_regex=r"(\d+\.\d+)",
        tags=["language", "scripting"],
    ),
    "rust": SkillDefinition(
        name="rust",
        display_name="Rust",
        category="scripting",
        description="Rust compiler",
        detect_command="rustc --version",
        version_regex=r"(\d+\.\d+)",
        tags=["language", "systems"],
    ),
    # ==================== DATABASES ====================
    "psql": SkillDefinition(
        name="psql",
        display_name="PostgreSQL Client",
        category="databases",
        description="PostgreSQL CLI",
        detect_command="psql --version",
        version_regex=r"(\d+\.\d+)",
        tags=["database", "postgresql", "sql"],
    ),
    "mysql": SkillDefinition(
        name="mysql",
        display_name="MySQL Client",
        category="databases",
        description="MySQL CLI",
        detect_command="mysql --version",
        version_regex=r"(\d+\.\d+)",
        tags=["database", "mysql", "sql"],
    ),
    "mongosh": SkillDefinition(
        name="mongosh",
        display_name="MongoDB Shell",
        category="databases",
        description="MongoDB CLI",
        detect_command="mongosh --version",
        version_regex=r"(\d+\.\d+)",
        tags=["database", "mongodb", "nosql"],
    ),
    "redis-cli": SkillDefinition(
        name="redis-cli",
        display_name="Redis CLI",
        category="databases",
        description="Redis CLI",
        detect_command="redis-cli --version",
        version_regex=r"(\d+\.\d+)",
        tags=["database", "redis", "cache"],
    ),
    "sqlite3": SkillDefinition(
        name="sqlite3",
        display_name="SQLite",
        category="databases",
        description="SQLite CLI",
        detect_command="sqlite3 --version",
        version_regex=r"(\d+\.\d+)",
        tags=["database", "sqlite"],
    ),
    "pg_dump": SkillDefinition(
        name="pg_dump",
        display_name="pg_dump",
        category="databases",
        description="PostgreSQL backup tool",
        detect_command="pg_dump --version",
        version_regex=r"(\d+\.\d+)",
        tags=["database", "postgresql", "backup"],
    ),
    # ==================== MONITORING ====================
    "prometheus": SkillDefinition(
        name="prometheus",
        display_name="Prometheus",
        category="monitoring",
        description="Monitoring system",
        detect_command="prometheus --version 2>&1 || echo 'not found'",
        version_regex=r"(\d+\.\d+)",
        tags=["monitoring", "metrics", "observability"],
    ),
    "grafana": SkillDefinition(
        name="grafana",
        display_name="Grafana",
        category="monitoring",
        description="Visualization and monitoring",
        detect_command="grafana-cli --version 2>&1 || echo 'not found'",
        tags=["monitoring", "visualization", "metrics"],
    ),
    "newrelic": SkillDefinition(
        name="newrelic",
        display_name="New Relic",
        category="monitoring",
        description="Application monitoring",
        detect_command="newrelic --version 2>&1 || echo 'not found'",
        tags=["monitoring", "apm", "cloud"],
    ),
    "datadog": SkillDefinition(
        name="datadog",
        display_name="Datadog",
        category="monitoring",
        description="Cloud monitoring",
        detect_command="dd --version 2>&1 || echo 'not found'",
        tags=["monitoring", "apm", "cloud"],
    ),
    # ==================== CONTAINER ====================
    "buildah": SkillDefinition(
        name="buildah",
        display_name="Buildah",
        category="container",
        description="Build container images",
        detect_command="buildah --version",
        version_regex=r"(\d+\.\d+)",
        tags=["container", "build"],
    ),
    "kaniko": SkillDefinition(
        name="kaniko",
        display_name="Kaniko",
        category="container",
        description="Build container images in Kubernetes",
        detect_command="kaniko --version 2>&1 || echo 'not found'",
        tags=["container", "kubernetes", "build"],
    ),
    "nerdctl": SkillDefinition(
        name="nerdctl",
        display_name="nerdctl",
        category="container",
        description="Docker-compatible CLI for containerd",
        detect_command="nerdctl --version",
        version_regex=r"(\d+\.\d+)",
        tags=["container", "containerd"],
    ),
    "skopeo": SkillDefinition(
        name="skopeo",
        display_name="Skopeo",
        category="container",
        description="Container image inspection",
        detect_command="skopeo --version",
        version_regex=r"(\d+\.\d+)",
        tags=["container", "registry"],
    ),
    "crictl": SkillDefinition(
        name="crictl",
        display_name="crictl",
        category="container",
        description="CRI-compatible container runtime CLI",
        detect_command="crictl --version",
        version_regex=r"(\d+\.\d+)",
        tags=["container", "kubernetes", "cri"],
    ),
    # ==================== GIT ====================
    "git": SkillDefinition(
        name="git",
        display_name="Git",
        category="git",
        description="Version control system",
        detect_command="git --version",
        version_regex=r"(\d+\.\d+)",
        tags=["vcs", "scm", "development"],
    ),
    "gh": SkillDefinition(
        name="gh",
        display_name="GitHub CLI",
        category="git",
        description="GitHub command line tool",
        detect_command="gh --version",
        version_regex=r"(\d+\.\d+)",
        tags=["github", "cli", "vcs"],
    ),
    "glab": SkillDefinition(
        name="glab",
        display_name="GitLab CLI",
        category="git",
        description="GitLab command line tool",
        detect_command="glab --version",
        version_regex=r"(\d+\.\d+)",
        tags=["gitlab", "cli", "vcs"],
    ),
    "hub": SkillDefinition(
        name="hub",
        display_name="hub",
        category="git",
        description="GitHub CLI wrapper",
        detect_command="hub --version",
        version_regex=r"(\d+\.\d+)",
        tags=["github", "cli", "vcs"],
    ),
    # ==================== ANALYTICS ====================
    "sonarqube": SkillDefinition(
        name="sonarqube",
        display_name="SonarQube",
        category="analytics",
        description="Code quality analysis",
        detect_command="sonar-scanner --version 2>&1 || echo 'not found'",
        tags=["quality", "analysis", "saas"],
    ),
    "cloc": SkillDefinition(
        name="cloc",
        display_name="cloc",
        category="analytics",
        description="Count lines of code",
        detect_command="cloc --version",
        version_regex=r"(\d+\.\d+)",
        tags=["analytics", "code-metrics"],
    ),
    "scc": SkillDefinition(
        name="scc",
        display_name="scc",
        category="analytics",
        description="Sloc Cloc Code (fast counter)",
        detect_command="scc --version",
        version_regex=r"(\d+\.\d+)",
        tags=["analytics", "code-metrics"],
    ),
    # ==================== DOCUMENTATION ====================
    "sphinx": SkillDefinition(
        name="sphinx",
        display_name="Sphinx",
        category="documentation",
        description="Python documentation generator",
        detect_command="sphinx-build --version",
        version_regex=r"(\d+\.\d+)",
        tags=["documentation", "python"],
    ),
    "docusaurus": SkillDefinition(
        name="docusaurus",
        display_name="Docusaurus",
        category="documentation",
        description="Static site generator for docs",
        detect_command="docusaurus --version 2>&1 || echo 'not found'",
        tags=["documentation", "react", "static-site"],
    ),
    "mdbook": SkillDefinition(
        name="mdbook",
        display_name="mdBook",
        category="documentation",
        description="Rust documentation generator",
        detect_command="mdbook --version",
        version_regex=r"(\d+\.\d+)",
        tags=["documentation", "rust"],
    ),
    # ==================== PACKAGE ====================
    "pip": SkillDefinition(
        name="pip",
        display_name="pip",
        category="package",
        description="Python package installer",
        detect_command="pip --version",
        version_regex=r"(\d+\.\d+)",
        tags=["python", "package", "package-manager"],
    ),
    "poetry": SkillDefinition(
        name="poetry",
        display_name="Poetry",
        category="package",
        description="Python dependency management",
        detect_command="poetry --version",
        version_regex=r"(\d+\.\d+)",
        tags=["python", "package", "dependency"],
    ),
    "pipenv": SkillDefinition(
        name="pipenv",
        display_name="Pipenv",
        category="package",
        description="Python dependency management",
        detect_command="pipenv --version",
        version_regex=r"(\d+\.\d+)",
        tags=["python", "package", "dependency"],
    ),
    "uv": SkillDefinition(
        name="uv",
        display_name="uv",
        category="package",
        description="Fast Python package manager",
        detect_command="uv --version",
        version_regex=r"(\d+\.\d+)",
        tags=["python", "package", "fast"],
    ),
    "conan": SkillDefinition(
        name="conan",
        display_name="Conan",
        category="package",
        description="C/C++ package manager",
        detect_command="conan --version",
        version_regex=r"(\d+\.\d+)",
        tags=["cpp", "package", "dependency"],
    ),
    # ==================== COMPLIANCE ====================
    "openpolicyagent": SkillDefinition(
        name="openpolicyagent",
        display_name="OPA",
        category="compliance",
        description="Open Policy Agent",
        detect_command="opa version",
        version_regex=r"(\d+\.\d+)",
        tags=["policy", "compliance", "security"],
    ),
    "conftest": SkillDefinition(
        name="conftest",
        display_name="conftest",
        category="compliance",
        description="Policy testing for IaC",
        detect_command="conftest --version",
        version_regex=r"(\d+\.\d+)",
        tags=["policy", "testing", "iac"],
    ),
    "sentinel": SkillDefinition(
        name="sentinel",
        display_name="Sentinel",
        category="compliance",
        description="HashiCorp policy framework",
        detect_command="sentinel --version 2>&1 || echo 'not found'",
        tags=["policy", "hashicorp", "compliance"],
    ),
}


def get_skill_by_name(name: str) -> Optional[SkillDefinition]:
    """Get skill definition by name."""
    return SKILL_DEFINITIONS.get(name.lower())


def get_skills_by_category(category: str) -> list[SkillDefinition]:
    """Get all skills in a category."""
    return [s for s in SKILL_DEFINITIONS.values() if s.category == category]


def get_all_categories() -> dict:
    """Get all skill categories with display info."""
    return SKILL_CATEGORIES


def get_skill_categories_list() -> list[str]:
    """Get list of category keys."""
    return list(SKILL_CATEGORIES.keys())


def list_all_skills() -> dict:
    """List all available skill definitions."""
    skills_list = []
    for name, skill in SKILL_DEFINITIONS.items():
        skills_list.append(
            {
                "name": name,
                "display_name": skill.display_name,
                "category": skill.category,
                "description": skill.description,
                "detect_command": skill.detect_command,
                "min_version": skill.min_version,
                "tags": skill.tags,
            }
        )

    return {
        "total": len(skills_list),
        "categories": SKILL_CATEGORIES,
        "skills": skills_list,
    }
